// Small honesty indicator: shows whether an AI answer came from live IBM
// Granite or the local simulation fallback.
export default function AiSourceBadge({ source }) {
  const live = source === 'granite';
  const color = live ? '#22d3ee' : '#64748b';
  const label = live ? 'GRANITE' : 'SIMULATED';
  return (
    <span
      title={live ? 'Answer generated by IBM Granite on watsonx.ai' : 'Answer from local simulation fallback'}
      className={`inline-flex items-center gap-[4px] text-[9px] font-bold tracking-[0.5px] rounded-[3px] px-[6px] py-[1px] border text-[${color}] border-[${color}44] bg-[${color}22]`}
    >
      <span className="w-[5px] h-[5px] rounded-full" style={{ background: color }} />
      {label}
    </span>
  );
}
